/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng ký tài khoản mới
         * @description Tạo Organization mới và User ADMIN đầu tiên.
         *     Người đăng ký đầu tiên của một org sẽ là ADMIN.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Đăng ký thành công */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["UserProfile"];
                            message?: string;
                        };
                    };
                };
                /** @description Email hoặc tên tổ chức đã tồn tại */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập
         * @description Xác thực và trả về JWT access token + refresh token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Đăng nhập thành công */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Email hoặc mật khẩu không đúng */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lấy profile của user hiện tại
         * @description Decode JWT và trả về thông tin user đang đăng nhập.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile của user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["UserProfile"];
                        };
                    };
                };
                /** @description Token không hợp lệ hoặc hết hạn */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách Projects trong Org */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Danh sách projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ProjectResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Tạo Project mới */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreateRequest"];
                };
            };
            responses: {
                /** @description Project đã được tạo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ProjectResponse"];
                        };
                    };
                };
                400: components["schemas"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        /** Chi tiết một Project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ProjectResponse"];
                        };
                    };
                };
                /** @description Project không tồn tại */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Xóa Project (soft delete)
         * @description Chỉ ADMIN mới được phép xóa project.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project đã được xóa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Không đủ quyền */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project không tồn tại */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Cập nhật Project */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectUpdateRequest"];
                };
            };
            responses: {
                /** @description Project đã được cập nhật */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ProjectResponse"];
                        };
                    };
                };
                /** @description Project không tồn tại */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách Tasks */
        get: {
            parameters: {
                query?: {
                    /** @description Lọc theo Project ID */
                    project_id?: string;
                    status?: "todo" | "in_progress" | "review" | "done" | "cancelled";
                    assignee_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Danh sách tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["TaskResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Tạo Task mới */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description UUID để tránh tạo trùng khi client retry */
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCreateRequest"];
                };
            };
            responses: {
                /** @description Task đã được tạo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["TaskResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        /** Chi tiết một Task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["TaskResponse"];
                        };
                    };
                };
                /** @description Task không tồn tại */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Xóa Task (soft delete)
         * @description Yêu cầu quyền MANAGER trở lên.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task đã được xóa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Không đủ quyền */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task không tồn tại */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Cập nhật Task
         * @description Cập nhật status, assignee, priority, v.v. Ghi AuditLog tự động.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskUpdateRequest"];
                };
            };
            responses: {
                /** @description Task đã được cập nhật */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["TaskResponse"];
                        };
                    };
                };
                /** @description Task không tồn tại */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @default false */
            success: boolean;
            message: string;
            /** @description Machine-readable error code (e.g. TASK_NOT_FOUND) */
            error_code?: string;
            details?: Record<string, never>;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            full_name: string;
            org_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenResponse: {
            /** @default true */
            success: boolean;
            data: {
                access_token: string;
                refresh_token: string;
                /** @default bearer */
                token_type: string;
            };
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            full_name: string;
            /** @enum {string} */
            role: "admin" | "manager" | "member" | "viewer";
            /** Format: uuid */
            org_id: string;
        };
        ProjectCreateRequest: {
            name: string;
            description?: string;
            /** @description Hex color code (e.g. */
            color?: string;
        };
        ProjectUpdateRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "paused" | "completed" | "archived";
            color?: string;
        };
        ProjectResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            /** @enum {string} */
            status: "active" | "paused" | "completed" | "archived";
            color?: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TaskCreateRequest: {
            title: string;
            /** Format: uuid */
            project_id: string;
            description?: string;
            /** @default 3 */
            priority_score: number;
            /**
             * Format: float
             * @description Estimated hours
             */
            estimated_time?: number;
            /** Format: date-time */
            deadline?: string;
            /** Format: uuid */
            assignee_id?: string;
        };
        TaskUpdateRequest: {
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "todo" | "in_progress" | "review" | "done" | "cancelled";
            priority_score?: number;
            estimated_time?: number;
            actual_time?: number;
            /** Format: uuid */
            assignee_id?: string;
            /** Format: date-time */
            deadline?: string;
        };
        TaskResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            org_id: string;
            description?: string;
            /** @enum {string} */
            status: "todo" | "in_progress" | "review" | "done" | "cancelled";
            priority_score: number;
            /** Format: float */
            estimated_time?: number;
            /** Format: float */
            actual_time?: number;
            /** @description Auto-generated by NLP (Phase 3) */
            tags?: string[];
            /** Format: uuid */
            assignee_id?: string;
            /** Format: uuid */
            created_by?: string;
            /** Format: date-time */
            deadline?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
